[package]
name = "omegga-anti-microbrick"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
brickadia = "0.1"
chrono = "0.4"
omegga = "0.2.11"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.10", features = ["full"] }
