[package]
name = "omegga-anti-microbrick"
version = "0.1.3"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
brickadia = "0.1.23"
chrono = "0.4"
omegga = "0.3.1"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.10", features = ["full"] }
uuid = "0.8.2"
