#!/bin/bash
FILE=omegga-anti-microbrick
BASE=$(dirname "$0")
DEBUG=./target/debug/
RELEASE=./target/release/
DIST=./bin/

cd $BASE
if test -f "$DEBUG$FILE"; then
    $DEBUG$FILE
elif test -f "$RELEASE$FILE"; then
    $RELEASE$FILE
else 
    $DIST$FILE
fi
